"""Add password reset columns to users table

Revision ID: 3aba76cb051b
Revises: a0a9870d88bb
Create Date: 2026-01-09 21:28:06.362679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aba76cb051b'
down_revision: Union[str, None] = 'a0a9870d88bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
